<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CENEP</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="shortcut icon" type="image/png" href="/img/favicon.ico">
</head>

<body>
    <?php include("../../inc/header.php"); ?>

    <section class="body mx-auto">
        <div class="contenedor-body row">
            <?php include("../../inc/menues/investigadores.php"); ?>

            <div class="body-texto col-md-9 p-5">
                <div class="contenedor-contenido">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a class="no-activo" href="/investigadores/investigadores.php">Investigadores/as</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Marcela Cerrutti</li>
                        </ol>
                    </nav>
                    <div class="encabezado-separador">
                        <h1>Marcela Cerrutti</h1>
                    </div>
                    <div class="texto">
                        <p><a href="cv/CVCerrutti_2020.pdf" target="_blank">cv completo | </a><a href="mailto:mcerrutti@cenep.org.ar">mcerrutti@cenep.org.ar</a> </p>
                        <p>Es  Licenciada y Profesora en Sociología de la Universidad de Buenos Aires, Master en Ciencias Sociales de la Facultad Latinoamericana de Sociología (FLACSO Buenos Aires) y Doctora en Sociología con especialidad en Demografía de la Universidad de Texas en Austin.  Fue becaria post-doctoral en el Population Studies Center de la Universidad de Pennsylvania. Es miembro de Carrera de Investigadores del Consejo Nacional de Investigaciones Científicas y Técnicas, CONICET (categoría Independiente). Es profesora titular regular en la Licenciatura en Sociología de la Universidad Nacional de San Martín. Ha dictado numerosos cursos de posgrado en el IDES-Universidad Nacional General Sarmiento, IDAES- Universidad Nacional de San Martín y en la Especialización en derecho de familia de la Facultad de Derecho de la Universidad de Buenos Aires. Fue profesora visitante en la Universidad de Texas en Austin. Fue directora del CENEP y vicepresidenta de la Asociación Latinoamericana de Población. Es actualmente es miembro de la Comisión Asesora de Sociología, Demografía y Ciencias de la Comunicación del CONICET y del panel científico sobre Migración Internacional de la Unión Internacional para el Estudios Científico de la Población (IUSSP 2018-2021). Ha coordinado numerosas investigaciones financiadas por organismos nacionales e internacionales (Fundación Ford, Fundación MacArthur, Save the Children, Comisión Europea, Ministerio de Educación, Ministerio de Ciencia y Tecnología e Innovación Productiva, Gobierno de la Ciudad Autónoma de Buenos Aires, Defensoría del Pueblo de la Provincia de Buenos Aires, Instituto de Políticas Publicas en Derechos Humanos del MERCOSUR) y ha sido consultora para UNICEF, UNFPA, CEPAL, CELADE, PNUD, BID, OIM y OPS. Cuenta con numerosas publicaciones nacionales e internacionales. Sus áreas de investigación se concentran en temas referidos a género, familia y trabajo; adolescencia y educación y migración internacional. Fue editora de la Revista Latinoamericana de Población y participa en numerosos comités editoriales de revistas académicas nacionales e internacionales.</p>
                        <h3>Investigaciones</h3>
                        <ul>
                            <li>Temporary versus Permanent Migration, TEMPER (proyecto colaborativo internacional, coordinadora Argentina)</li>
                            <li>Patrones emergentes de la migración sudamericana: los argentinos en España en perspectiva comparada</li>
                            <li>La integración educativa y social de los adolescentes inmigrantes en grandes centros urbanos de la Argentina
                            <li>El acceso a derechos de los inmigrantes en la provincia de Buenos Aires</li>
                            <li>Migración y Salud Sexual y Reproductiva de las Mujeres y los Jóvenes Bolivianos en la Argentina</li>
                            <li><a href="investigaciones/cerrutti/02_07_12.html" onclick="window.open('investigaciones/cerrutti/02_07_12.html','','scrollbars=yes,width=500,height=600');return false;">La institución escolar del nivel medio y su rol en el pasaje a la educación superior
                            <li><a href="investigaciones/cerrutti/02_07_11.html" onclick="window.open('investigaciones/cerrutti/02_07_11.html','','scrollbars=yes,width=500,height=600');return false;">El derecho a la educación de los niños/as y adolescentes indígenas: Estado de Situación en Argentina, desafíos y recomendaciones
                            <li><a href="investigaciones/cerrutti/02_01_19.html" onclick="window.open('investigaciones/cerrutti/02_01_19.html','','scrollbars=yes,width=500,height=600');return false;">Salud y migración en el contexto de la integración económica: el caso de Argentina y Paraguay
                            <li><a href="investigaciones/cerrutti/02_04_02.html" onclick="window.open('investigaciones/cerrutti/02_04_02.html','','scrollbars=yes,width=500,height=600');return false;">La generación, formas de envío y utilización de remesas en la migración paraguaya a la Argentina 
                            <li><a href="investigaciones/cerrutti/02_04_06.html" onclick="window.open('investigaciones/cerrutti/02_04_06.html','','scrollbars=yes,width=500,height=600');return false;">La urbanización latinoamericana a fines del siglo XX: un estudio comparativo. El caso de Argentina 
                            <li>Migración, familia y maternidad de mujeres paraguayas en la Argentina</li>
                            <li><a href="investigaciones/cerrutti/02_04_07.html" onclick="window.open('investigaciones/cerrutti/02_04_07.html','','scrollbars=yes,width=500,height=600');return false;">Dinámica e impacto de la migración del Perú y del Paraguay a la Argentina </a></li>
                            <li><a href="investigaciones/cerrutti/02_04_03.html" onclick="window.open('investigaciones/cerrutti/02_04_03.html','','scrollbars=yes,width=500,height=600');return false;">Inserción ocupacional y trayectoria laboral de migrantes paraguayos y peruanos en el Área Metropolitana de Buenos Aires </a></li>
                            <li><a href="investigaciones/cerrutti/02_04_08.html" onclick="window.open('investigaciones/cerrutti/02_04_08.html','','scrollbars=yes,width=500,height=600');return false;">Tendencias recientes de la urbanización en América Latina </a></li>
                            <li><a href="investigaciones/cerrutti/02_07_03.html" onclick="window.open('investigaciones/cerrutti/02_07_03.html','','scrollbars=yes,width=500,height=600');return false;">Modelos de gestión, autonomía institucional y logros educativos en la enseñanza media argentina </a></li>
                            <li><a href="inves" onclick="window.open('investigaciones/cerrutti/02_07_05.html','','scrollbars=yes,width=500,height=600');return false;">La enseñanza de nivel medio en la Argentina: lugar clave para la formación para la vida y el trabajo: <>El abandono escolar en el nivel medio en la Argentina</a></li>
                            <li><a href="investigaciones/cerrutti/02_01_19.html" onclick="window.open('investigaciones/cerrutti/02_01_19.html','','scrollbars=yes,width=500,height=600');return false;">Determinantes de la reinserción de desertores de nivel medio en el sistema educativo en áreas urbanas de la Argentina (1997-2002) </a>
                            <li><a href="investigaciones/cerrutti/02_01_10.html" onclick="window.open('investigaciones/cerrutti/02_01_10.html','','scrollbars=yes,width=500,height=600');return false;">Evaluando la calidad de los servicios reproductivos en Buenos Aires: de la perspectiva de las usuarias a una medición estandarizada </a></li>
                            <li><a href="investigaciones/cerrutti/02_05_06.html" onclick="window.open('investigaciones/cerrutti/02_05_06.html','','scrollbars=yes,width=500,height=600');return false;">Cambios en las actitudes sobre aspectos de la familia</a></li>
                        </ul>
                        <h3>Publicaciones</h3>
                        <p><strong>Cerrutti, M. y E. Parrado (2020)</strong> “Migrations in South America” <em>Sage Handbook on International Migration</em>, en Christine Inglis, Wei Li y Binod Khadria, (Eds.). Los Angeles: Sage Reference.</p>
                        <p><strong>Cerrutti, M. (2020)</strong> Estudiantes inmigrantes en las escuelas primarias y secundarias de la Ciudad Autónoma de Buenos Aires. Buenos Aires: Organización de Estados Iberoamericanos para la Educación, la Ciencia y la Cultura; Ministerio de Educación de la Ciudad de Buenos Aires <a href="https://oei.org.ar/wp-content/uploads/2020/01/4-Estudiantes-inmigrantes-Cerrutti-web.pdf">https://oei.org.ar/wp-content/uploads/2020/01/4-Estudiantes-inmigrantes-Cerrutti-web.pdf</a></p>
                        <p><strong>Binstock G. y M. Cerrutti (2019)</strong> Condición migratoria y resultados de aprendizaje. APRENDER 2017. Buenos Aires: Secretaría de Evaluación Educativa, Ministerio de Educación de la Nación. <a href="https://www.argentina.gob.ar/sites/default/files/migrantes-2017.pdf">https://www.argentina.gob.ar/sites/default/files/migrantes-2017.pdf</a></p>
                        <p><strong>Cerrutti, M. y G. Binstock (2019)</strong> “Migración, adolescencia y educación en Argentina: desentrañando las brechas de aprendizajes” en <em>Revista Latinoamericana de Población</em>, RELAP, Vol. 13, Num. 24: 36-62. <a href="https://doi.org/10.31406/relap2019.v13.i1.n24.2">https://doi.org/10.31406/relap2019.v13.i1.n24.2</a></p>
                        <p><strong>Cerrutti M y M. Koolhaas (2018)</strong> Evaluación de la implementación del Acuerdo sobre Residencia el MERCOSUR y su incidencia en el acceso a derechos de los migrantes, <em>Cuadernos Migratorios</em> Num. 9, Organización Internacional para las Migraciones, OIM. <a href="https://publications.iom.int/system/files/pdf/estudio_sobre_la_evaluacion_y_el_impacto_del_acuerdo_de_residencia_del_mercosur.pdf">https://publications.iom.int/system/files/pdf/estudio_sobre_la_evaluacion_y_el_impacto_del_acuerdo_de_residencia_del_mercosur.pdf</a></p>
                        <p><strong>Cerrutti, M.; M. Beheran; K. Donato y S. Giorguli (2018)</strong> Strengthening data on migration to inform policy making en <em>Global Solutions Journal</em>. Vol 1, Num 2: 174-180. <a href="https://www.ifw-kiel.de/fileadmin/Dateiverwaltung/IfW_Unit/Global_Challenges_Center/Text/GlobalSolutionsJournal_2_2018_E-Reader.pdf">https://www.ifw-kiel.de/fileadmin/Dateiverwaltung/IfW_Unit/Global_Challenges_Center/Text/GlobalSolutionsJournal_2_2018_E-Reader.pdf</a></p>
                        <p><strong>Cerrutti, M. (2018)</strong> “Migrantes y migraciones: nuevas tendencias y dinámicas” en Juan Ignacio Piovani y Agustín Salvia (Coords.) <em>La sociedad argentina en el siglo XXI. Cómo somos, vivimos y convivimos en una sociedad desigual</em>. Buenos Aires: Siglo XXI.</p>
                        <p><strong>Cerrutti, M. (2017)</strong> “MERCOSUR and Regional Migration: a Human Rights Approach” in Tulia Falleti and Emilio Parrado (eds.), <em>Latin America since the Left Turn</em>, Philadelphia: University of Pennsylvania Press.</p>
                        <p><strong>Cerrutti, M. (2017)</strong> “Desatando nudos: género, familia y migración en la Argentina” en Eleonor Faur (Comp.) <em>Mujeres y varones en la Argentina de hoy. Géneros en movimiento</em>. Buenos Aires: Siglo XXI y Fundación OSDE.</p>
                        <p><strong>Binstock, M. y M. Cerrutti (2016)</strong> “Adolescentes inmigrantes en escuelas medias de Buenos Aires: experiencias de discriminación y barreras para la integración” en <em>Desarrollo Económico</em>, Num. 217, Instituto de Desarrollo Económico y Social, IDES, Buenos Aires, Argentina.</p>
                        <p><strong>Cerrutti, M. (en prensa)</strong> “MERCOSUR and Regional Migration: a Human Rights Approach” in Tulia Falleti and Rogers Smith (eds.), Post-Neoliberal Latin America, Philadelphia: University of Pennsylvania Press.</p>
                        <p><strong>Cerrutti, M y Maguid A. (2016)</strong> “Crisis económica en España y el retorno de inmigrantes sudamericanos” en Migraciones Internacionales, El Colegio de la Frontera Norte, México.</p>
                        <p><strong>Cerrutti, M. (2015)</strong> “Intraregional Migration in South America: Trends and a Research Agenda” Annual Review of Sociology 41.</p>
                        <p><strong>Cerrutti, M. (2015)</strong> “Buenos Aires, ciudad de inmigración”, Coyuntura Demográfica, Num 7: 51-58. El Colegio de México. Ciudad de México.</p>
                        <p><strong>Binstock, G.; Cerrutti, M. y Maguid, A. (2014)</strong> “Pautas de reunificación familiar de las inmigrantes sudamericanas en España”, Estudios Migratorios Latinoamericanos, Año 26, Num 73, Jul-Dic 2012, pp.3-27. Buenos Aires, CEMLA.</p>
                        <p><strong>Cerrutti, M. (2014)</strong> “Migración internacional en América Latina: tendencias y retos para la acción.”, en Laura Rodríguez Wong; José Eustáquio Alves; Jorge Rodríguez Vignoli; Cássio Maldonado Turra (Organizadores) Cairo+20: perspectivas de la agenda de población y desarrollo sostenible después de 2014. Serie Investigaciones 15, Río de Janeiro: Asociación Latinoamericana de Población.</p>
                        <p><strong>Cerrutti, M. y Grimson, A. (2013)</strong> “Neoliberal Reform and Protest in Buenos Aires” en Mark Goodale y Nancy Postero (Eds.), Neoliberalism, Interrupted Social Change and Contested Governance in Contemporary Latin America. Stanford: Stanford University Press.</p>
                        <p><strong>Cerrutti, M, Maguid A. y Binstock, G. (2013)</strong> “Familia, migración y cadenas globales de cuidado” en Natalia Gherardi, Laura Pautassi y Carla Zibecchi Redefiniendo las fronteras del cuidado. Agenda, derechos e infraestructura, Buenos Aires: ELA.</p>
                        <p><strong>Cerrutti, M. y Morlacchetti, A. (Coords.) (2013)</strong> “El acceso a derechos de las personas migrantes en la provincia de Buenos Aires” Buenos Aires: Instituto de Políticas Públicas en Derechos Humanos del Mercosur y Defensor del Pueblo de la Provincia de Buenos Aires. </p>
                        <p><strong>Cerrutti, M. y Binstock, G. (2012) </strong><em>Los estudiantes inmigrantes en la escuela secundaria. Integración y desafíos</em>. Buenos Aires: UNICEF. <a href="http://www.unicef.org/argentina/spanish/estudiantes_secundarios_inmigrantes_2012.pdf">http://www.unicef.org/argentina/spanish/estudiantes_secundarios_inmigrantes_2012.pdf</a></p>
                        <p><strong>Marcelino, P. y Cerrutti, M. (2012)</strong> Recent African immigration to South America: The Cases of Argentina and Brazil in the Regional Context, en Jorge Martinez y Leandro Reboiras (Eds.) <em>Development, Institutional and Policy Aspects of International Migration Between Africa, Europe and Latin America. </em>Santiago, Chile:Economic Commission for Latin America and The Caribean, ECLAC. <a href="http://www.eclac.org/publicaciones/xml/8/46188/W_InternationalMig_FINAL.pdf">http://www.eclac.org/publicaciones/xml/8/46188/W_InternationalMig_FINAL.pdf</a></p>
                        <p><strong>Cerrutti, M y Maguid A. (2011)</strong> “Migrantes Sudamericanos en España: Tendencias Recientes y perfil de sus migrantes”, en <em>Migrantes Sudamericanos en España: Panorama y Políticas. </em>Cuadernos Migratorios Num. 1, Organización Internacional para las Migraciones. Buenos Aires: OIM, Oficina Regional para América del Sur. <a href="http://www.iom.int/jahia/webdav/shared/shared/mainsite/published_docs/serial_publications/OIM-Migrantes-Sudamericanos-en-Espana-No1.pdf">http://www.iom.int/jahia/webdav/shared/shared/mainsite/published_docs/serial_publications/OIM-Migrantes-Sudamericanos-en-Espana-No1.pdf</a></p>
                        <p><strong>Cerrutti, M (2011) </strong><em>Salud y Migración Internacional Mujeres Bolivianas en la Argentina</em>. Buenos Aires: Fondo de Población de las Naciones Unidas, UNFPA y Centro de Estudios de Población, CENEP. <a href="http://www.unfpaargentina.com.ar/sitio/archivos/mujeresbolivianasenargentina.pdf">http://www.unfpaargentina.com.ar/sitio/archivos/mujeresbolivianasenargentina.pdf</a></p>
                        <p><strong>Cerrutti, M. y Gaudio M. (2010)</strong> “Gender differences between Mexican migration to the United States and Paraguayan migration to Argentina” en Donato, K. M., Hiskey J., Durand J., y Masse, D.S.  Continental Divides:  International Migration in the Americas, Número Especial  de <em>The ANNALS of the American Academy of Social and Political Science</em>.</p>
                        <p><strong>Cerrutti, M. y Maguid, A. (2010) </strong>“Familias divididas y cadenas globales de cuidado: la migración sudamericana a España” Serie Políticas Sociales Num. 163. División de Desarrollo Social, CEPAL, Santiago de Chile. <a href="http://www.eclac.cl/cgi-bin/getProd.asp?xml=/publicaciones/xml/9/40519/P40519.xml&amp;xsl=/dds/tpl/p9f.xsl&amp;base=/tpl-i/top-bottom.xslt">http://www.eclac.cl/cgi-bin/getProd.asp?xml=/publicaciones/xml/9/40519/P40519.xml&amp;xsl=/dds/tpl/p9f.xsl&amp;base=/tpl-i/top-bottom.xslt</a></p>
                        <p><strong>Duro, E.; Cerrutti, M. y Binstock, G. (2009) </strong><em>Situación socioeducativa de niñas, niños y adolescentes de comunidades rurales wichí y mbyá guaraní</em>. Buenos Aires: UNICEF. <a href="http://www.unicef.org/argentina/spanish/Libro_EIB.pdf">http://www.unicef.org/argentina/spanish/Libro_EIB.pdf</a></p>
                        <p><strong>Cerrutti, M. (2009)</strong> “Diagnóstico de las poblaciones de inmigrantes en la Argentina” en <em>Serie de Documentos de la Dirección Nacional de Población</em>, Num 02<em>. </em>Buenos Aires: Dirección Nacional de Población, Secretaría del Interior. <a href="http://www.mininterior.gov.ar/cofepo/otras_publicaciones.asp">http://www.mininterior.gov.ar/cofepo/otras_publicaciones.asp</a></p>
                        <p><strong>Cerrutti, M. y Binstock, G. (2009)</strong> “Familias latinoamericanas en transformación: los desafíos y demandas para la acción pública” Serie Políticas Sociales Num. 147, División de Desarrollo Social, Comisión Económica para América Latina y el Caribe, CEPAL, Santiago de Chile. <a href="http://www.eclac.cl/publicaciones/xml/8/37438/sps147-Familias-latinoamericanas.pdf">http://www.eclac.cl/publicaciones/xml/8/37438/sps147-Familias-latinoamericanas.pdf</a></p>
                        <p><strong>Cerrutti, M. (2009)</strong> “Gender and Intra-regional regional migration in South America” en <em>Human Development Research Papers </em>2009/12. United Nations Development Programme. <a href="http://hdr.undp.org/en/reports/global/hdr2009/papers/">http://hdr.undp.org/en/reports/global/hdr2009/papers/</a></p>
                        <p><strong>Cerrutti, M. y Parrado, E. (2007)</strong> “The remittances of Paraguayan migrants to Argentina: their prevalence, amount, and utilization”, <em>Integration and Trade Journal</em>, Julio-Diciembre 2007. Banco Interamericano de Desarrollo.</p>
                        <p><strong>Cerrutti, M. y Bertoncello, R. (2006)</strong> “Urbanization and Internal Migration Patterns in Latin America” Marta Tienda and Sally Findley, Preston-Whyte, E. y Tollman, S.  (eds.) <em>Africa on the Move:</em><em>African Migration and Urbanization in Comparative Perspective</em>.  Witwatersrand University Press.</p>
                        <p><strong>Cerrutti, M. y Grimson, A. (2005)</strong> “Buenos Aires, neoliberalismo y después. Cambios socioeconómicos y respuestas populares”, en Alejandro Portes, Bryan Roberts y Alejandro Grimson (ed.), <em>La ciudad latinoamericana.</em> Buenos Aires: Prometeo.</p>
                        <p><strong>Cerrutti, M. (2005)</strong> “La migración peruana a la Argentina: su evolución y características” en <em>Población de Buenos Aires</em>, Año 2 (2): 7-25.</p>
                        <p><strong>Binstock, G. y Cerrutti, M. (2005) </strong><em>Carreras Truncadas: El Abandono en el Nivel Medio en la Argentina.</em> Buenos Aires: UNICEF.</p>
                        <p><strong>Cerrutti, M. y Massey, D. (2004)</strong> “Trends in Mexican Migration to the United States 1965 to 1995” en Jorge Durand y Douglas Massey (Eds.) <em>Crossing the Border. </em><em>Research from the Mexican Migration Project”.</em> New York: Russell Sage.</p>
                        <p><strong>Parrado, E. y Cerrutti. M. (2003)</strong>  “Labor Migration between Developing Countries: the Case of Paraguay and Argentina”, <em>International Migration Review</em>, 37(1):101-132.</p>
                        <p><strong>Cerrutti, M. (2003)</strong>  “Trabajo, Organización Familiar y Relaciones de Género en Buenos Aires”, en Wainerman, Catalina (Ed.) <em>Familia, Trabajo y Género. Un mundo de nuevas relaciones</em>. Buenos Aires: UNICEF/Fondo de Cultura Económica</p>
                        <p><strong>Cerrutti, M. y Parrado, E. (</strong><strong>2002)</strong> “Migración Laboral de Paraguayos a la Argentina:  Entrada a los Mercados Trabajo y       Trayectorias Ocupacionales” en <em>Estudios Migratorios Latinoamericanos</em>. Num 48:369-399.</p>
                        <p><strong>Cerrutti, M. y Massey, D. (2001)</strong> “On the Auspices of Female Mexican Migration to the United States”, <em>Demography</em>, Vol 38(2): 187-200.</p>
                        <p><strong>Cerrutti, M. (2000)</strong> “Economic Reform, Structural Adjustment and Female Participation in the Labour Force in  Buenos Aires, Argentina”. <em>World Development</em>, 28/5.</p>
                        <p><strong>Cerrutti, M. (2000)</strong>  “Intermittent Employment among Married Women: A Comparative Study of Buenos Aires and Mexico City”. <em>Journal of Comparative Family Studies</em>. 31/1: 19-43<em>.</em></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include("../../inc/footer.php"); ?>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

</html>