<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CENEP</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="shortcut icon" type="image/png" href="/img/favicon.ico">
</head>


<body>
    <?php include("../inc/header.php"); ?>

    <section class="body mx-auto">
        <div class="contenedor-body row">
            <?php include("../inc/menues/areas-tematicas.php"); ?>

            <div class="body-texto col-md-9 p-5">
                <div class="contenedor-contenido">
                    <div class="encabezado-separador">
                        <h1>Fecundidad, salud reproductiva</h1>
                    </div>
                    <div class="texto">
                        <p>Esta área temática es objeto de amplio tratamiento en el CENEP. Dando continuidad a los estudios sobre niveles y tendencias de la fecundidad, el área incluye también el tratamiento de las cuestiones relacionadas con la salud reproductiva y sus relaciones con la mortalidad. Se estudian además las condiciones de atención en los servicios de salud y se analizan y evalúan planes y programas específicos de intervención. También se pone énfasis en la relación con las cuestiones de género y en el rol de los varones en la salud reproductiva propia y la de las mujeres.</p>
                        <h3>Investigaciones</h3>
                        <ul>
                            <li><a href="fecundidad/1.php">La salud reproductiva de las mujeres en la Argentina: Resultados de la Encuesta Nacional de Nutrición y Salud</a></li>
                            <li><a href="fecundidad/2.php">Morbilidad materna severa en la Argentina: prevención y calidad de la atención para reducir la incidencia y consecuencias adversas del aborto</a></li>
                            <li><a href="fecundidad/3.php">Las políticas públicas en salud sexual y reproductiva y su adecuación al imaginario y las prácticas de los jóvenes con respecto a su sexualidad</a></li>
                            <li><a href="fecundidad/4.php">Las tecnologías reproductivas en la Argentina actual: los factores de su elección como respuesta a la infertilidad, frente a la adopción o a la ausencia de hijos</a></li>
                            <li><a href="fecundidad/5.php">Salud sexual y reproductiva adolescente en América latina y el Caribe </a></li>
                            <li><a href="fecundidad/6.php">El fenómeno de la coerción en la sexualidad adolescente. Derechos humanos y sexualidad</a></li>
                            <li><a href="fecundidad/7.php">Promoción de la participación de los hombres en la salud sexual y reproductiva en Centroamérica. Análisis comparativo</a> </li>
                            <li><a href="fecundidad/8.php">La fecundidad adolescente en Argentina: diagnóstico sociodemográfico </a></li>
                            <li><a href="fecundidad/9.php">Educación para la vida: diseño y evaluación de intervenciones para la prevención de la salud sexual y reproductiva en adolescentes </a></li>
                            <li><a href="fecundidad/10.php">Evaluando la calidad de los servicios reproductivos en Buenos Aires: de la perspectiva de las usuarias a una medición estandarizada</a></li>
                            <li><a href="fecundidad/11.php">Línea de base para el Programa Nacional de Salud Reproductiva y Procreación Responsable</a></li>
                            <li><a href="fecundidad/12.php">Dominación y violencia en grupos de varones históricamente autosegregados que inician un proceso de feminización: el caso del Ejército Argentino y la Prefectura Nacional Argentina</a></li>
                            <li><a href="fecundidad/13.php">Promoviendo el involucramiento y la participación de los varones en la salud sexual y reproductiva: insumos para la elaboración de una estrategia comunicacional </a></li>
                            <li><a href="fecundidad/14.php">Comenzando a descifrar el misterio: el compromiso del varón en la salud reproductiva </a></li>
                            <li><a href="fecundidad/15.php">Investigación comparativa (Argentina, Bolivia, Cuba y Perú) sobre la realidad y creencias en los procesos de toma de decisiones sexuales y reproductivas: las percepciones y los comportamientos masculinos </a></li>
                            <li><a href="fecundidad/16.php">Los varones frente al aborto</a> </li>
                            <li><a href="fecundidad/17.php">Realidad y creencias en los procesos de toma de decisiones sexuales y reproductivas: las percepciones y los comportamientos masculinos</a> </li>
                            <li><a href="fecundidad/18.php">Atención de la salud de las adolescentes: las respuestas desde lo institucional (gobierno nacional, gobierno municipal y servicios hospitalarios)</a></li>
                            <li><a href="fecundidad/19.php">Salud y migración en el contexto de la integración económica: el caso de Argentina y Paraguay </a></li>
                            <li><a href="fecundidad/20.php">Comenzando a descifrar el misterio: el compromiso del varón en la salud reproductiva</a> </li>
                            <li><a href="fecundidad/21.php">Actividad económica femenina, migraciones y reproducción en ciudades latinoamericanas entre 1970 y 1990</a> </li>
                            <li><a href="fecundidad/22.php">Yo no quería pero... Iniciación sexual bajo coerción en adolescentes mujeres </a></li>
                            <li><a href="fecundidad/23.php">Factores culturales y psicosociales en la prevención y el tratamiento de las enfermedades de transmisión sexual. Poder, afecto y placer en las negociaciones entre géneros </a></li>
                            <li><a href="fecundidad/24.php">Salud reproductiva: ¿una cuestión de dos? </a></li>
                            <li><a href="fecundidad/25.php">Adquisición de pautas de cuidado de la salud reproductiva entre las adolescentes: la transmisión de madres a hijas </a></li>
                            <li><a href="fecundidad/26.php">El método del hijo previo y la mortalidad infantil e intrauterina en Zárate </a></li>
                            <li><a href="fecundidad/27.php">Mortalidad materna en barrios de Zárate: encuesta demográfica para medirla mediante el método de la sobrevivencia de hermanas</a></li>
                            <li><a href="fecundidad/28.php">Imágenes de género y conducta reproductiva en la adolescencia </a></li>
                        </ul>
                        <h3>Publicaciones</h3>
                        <p><strong>Ariza, L. (2006) </strong><em>Tecnologías reproductivas en la Argentina contemporánea: la experiencia de la infertilidad en mujeres usuarias.</em> Trabajo presentado en el V Taller de investigaciones sociales en salud reproductiva y sexualidad, organizado por CENEP, CEDES y Comisión Científica de Nupcialidad y Reproducción de AEPA, Buenos Aires, 17-19 de abril. (Trabajo aceptado para su publicación en Avances en investigación sobre salud reproductiva y sexualidad, Vol.II. Buenos Aires: CENEP - CEDES - AEPA).</p>
                        <p><strong>Ariza, L. (2006) </strong><em>La experiencia de la infertilidad en mujeres que optan por tratamientos de reproducción asistida: ¿fracaso de género o triunfo inexorable?</em> Trabajo presentado en el VII Seminário Internacional Fazendo Gênero VII: Gênero e Preconceitos, organizado por Universidade Federal de Santa Catarina y Universidade do Estado de Santa Catarina, Florianópolis, 28-30 de agosto.</p>
                        <p><strong>Binstock, G. y M. Cerrutti. (2006) </strong><em>Youth and Health: Evidence from the Study of Youth and Social Conditions Survey.</em> Informe final de investigación. Buenos Aires: CENEP. Mimeo.</p>
                        <p><strong>Pantelides, E. A. (2006) </strong><em>La transición de la fecundidad en la Argentina 1869-1947.</em> Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 54.</p>
                        <p><strong>Pantelides, E. A. (2006) </strong>“Maternidad en la adolescencia”. <em>Novedades Educativas,</em> 184: 54-57.</p>
                        <p><strong>Pantelides, E. A. (2006) </strong><em>Tendencias recientes y diferenciales de la fecundidad adolescente en América latina y el Caribe.</em> Trabajo presentado en el II Congreso de la Asociación Latinoamericana de Población, ALAP, Guadalajara (México), 3-5 de septiembre.</p>
                        <p><strong>Pantelides, E. A. y H. Manzelli (2006) </strong><em>La edad a la iniciación sexual y sus correlatos en varones de cuatro ciudades de América latina.</em> Trabajo presentado en el V Taller de Investigaciones Sociales en Salud Reproductiva y Sexualidad, organizado por CENEP, CEDES y Comisión Científica de Nupcialidad y Reproducción de AEPA, Buenos Aires, 17-19 de abril.</p>
                        <p><strong>Binstock, G. y E. A. Pantelides (2005)</strong> La fecundidad adolescente hoy: diagnóstico sociodemográfico. En: M. Gogna (coord.) <em>Embarazo y maternidad en la adolescencia. Estereotipos, evidencias y propuestas para políticas públicas.</em> Buenos Aires: CEDES-Ministerio de Salud y Ambiente de la Nación-UNICEF Argentina.</p>
                        <p><strong>Infesta Domínguez, G. (2005)</strong> "Estudios sobre seguridad y género”. <em>Guardacostas. Revista Oficial de la Prefectura Naval Argentina,</em> 61(116): 16-21, abril.</p>
                        <p><strong>Infesta Domínguez, G. y M. J. Llanos Pozzi (2005) </strong><em>Reflexiones en torno a los problemas y desafíos para la puesta en práctica de un programa de Educación Sexual.</em> Trabajo presentado al Coloquio Interdisciplinario “Educación, sexualidades y relaciones de género. Investigaciones y experiencias”, Buenos Aires, Facultad de Filosofía y Letras de la Universidad de Buenos Aires, 4 al 6 de agosto.</p>
                        <p><strong>Infesta Domínguez, G. (2005) </strong>Decisiones anticonceptivas en la pareja desde la perspectiva de varones adultos. En: Pantelides, E. A. y E. López (comps.), <em>Varones latinoamericanos. Estudios sobre sexualidad y reproducción.</em> Buenos Aires: Paidós, pp. 145-173.</p>
                        <p><strong>López, E. y E. A. Pantelides (2005) </strong>Introducción. En: E. A. Pantelides y E. López (comps).<em>Varones latinoamericanos. Estudios sobre sexualidad y reproducción.</em> Buenos Aires: Paidós, pp. 23-26.</p>
                        <p><strong>Pantelides, E. A. (2005) </strong><em>Necesidades de servicios de salud reproductiva en varones centroamericanos.</em> Trabajo presentado en la XVIII Reunión Bienal de la Asociación Latinoamericana de Investigadores en Reproducción Humana (ALIRH). Cartagena de Indias (Colombia), 11-13 de mayo.</p>
                        <p><strong>Pantelides, E. A. (2005) </strong>La medición de un concepto. Reflexiones a partir de una investigación sobre coerción sexual. En: L. Álvarez Vázquez y A. Rodríguez (coords.) <em>La investigación en salud sexual y reproductiva. Propuestas metodológicas y experiencias prácticas.</em> La Habana: Publicaciones Azucareras, pp. 84-93.</p>
                        <p><strong>Pantelides, E. A. y H. Manzelli (2005) </strong><em>La salud sexual y reproductiva: también un asunto de hombres.</em> Buenos Aires: OPS, Bundesministerium für wirtschaftliche Zusammenarbait und Entwicklung.</p>
                        <p><strong>Pantelides, E. A y H. Manzelli (2005) </strong>“Violencia en la pareja. Evidencias a partir de encuestas a hombres centroamericanos”. <em>Papeles de Población,</em> 11(45): 247-270.</p>
                        <p><strong>Pantelides, E. A y E. López, comps. (2005)</strong> <em>Varones latinoamericanos. Estudios sobre sexualidad y reproducción.</em> Buenos Aires: Paidós.</p>
                        <p><strong>Pantelides, E. A. (2005) </strong>“La transición de la fecundidad en la Ciudad de Buenos Aires. Una aproximación”. Población de Buenos Aires. Revista de la Dirección General de Estadística y Censos del Gobierno del la Ciudad Autónoma de Buenos Aires, 1 (1): 35-42.</p>
                        <p><strong>Alvarez, L., A. Rodríguez, G. Infesta Domínguez y J. L. Calero (2004) </strong>Enfoque metodológico cualitativo en las investigaciones en Salud Sexual y Reproductiva. En: L. Alvarez, y A. Rodríguez (coords.), <em>La investigación en Salud Sexual y Reproductiva: propuestas metodológicas y experiencias.</em> La Habana: UNFPAP/OMS, pp. 50-71.</p>
                        <p><strong>Alvarez, L., A. Rodríguez y G. Infesta Domínguez (2004)</strong> Enfoque metodológico combinado en las investigaciones en Salud Sexual y Reproductiva. En: L. Alvarez y A. Rodríguez (coords.), <em>La investigación en Salud Sexual y Reproductiva: propuestas metodológicas y experiencias.</em> La Habana: UNFPA/OMS, pp. 72-83.</p>
                        <p><strong>Cerrutti, M. y B. Freidin (2004) </strong><em>Evaluación de calidad en servicios públicos de planificación familiar: medidas estandarizadas y la perspectiva de las usuarias.</em> Trabajo presentado en el V Seminario de Salud y Política Pública, organizado por el CEDES, Buenos Aires, septiembre.</p>
                        <p><strong>Cerrutti, M. y B. Freidin (2004) </strong><em>Analyzing the Quality of Family Planning Services in Buenos Aires: Convergence and Discrepancy between Users’ and Experts’ Views.</em> Trabajo presentado en el Congreso de la Latin American Studies Association, Las Vegas, 7-9 de octubre.</p>
                        <p><strong>Geldstein, R. N. y M. L. Schufer (2004) </strong>Género, sexo y salud reproductiva. Prácticas e ideas de los varones jóvenes de Buenos Aires. En: L. Álvarez y A. Rodríguez (comps.) <em>La investigación en Salud Sexual y Reproductiva: propuestas metodológicas y experiencias prácticas.</em> La Habana: UNFPA y Publicaciones Azucareras MINAZ.</p>
                        <p><strong>Geldstein, R. N. y M. L. Schufer (2004)</strong> Después del debut, ¿qué?: una mirada a la sexualidad de los varones jóvenes de Buenos Aires. En: E. A. Pantelides y E. M. López (comps.) <em>Varones latinoamericanos. Estudios sobre sexualidad y reproducción.</em> Buenos Aires: Paidós.</p>
                        <p><strong>Pantelides, E. A. (2004) </strong>“Aspectos sociales del embarazo y la fecundidad adolescente en América Latina”. <em>Notas de Población,</em> 31 (78): 7-34.</p>
                        <p><strong>Infesta Domínguez, G. (2003) </strong>Conductas de cuidado de la salud sexual y reproductiva en varones adultos: una cuestión de carreras. En: A. Mendes Diz, A. Federico, L. Findling y M. Abramzón (eds.), <em>IV Jornadas Nacionales de Debate Interdisciplinario en Salud y Población,</em>Instituto de Investigaciones Gino Germani, Facultad de Ciencias Sociales, Universidad de Buenos Aires, Buenos Aires (formato electrónico en CD).</p>
                        <p><strong>Geldstein, R. N. y E. A Pantelides (2003)</strong> Coerción, consentimiento y deseo en “la primera vez”. En: S. Checa (comp.), <em>Género, sexualidad y derechos reproductivos en la adolescencia.</em> Buenos Aires: Paidós, pp. 103- 138.</p>
                        <p><strong>Geldstein, R. N. y E. A. Pantelides (2003) </strong>Coerción, consentimiento y deseo en la primera vez. En: S. Checa (comp.) <em>Género, salud y derechos reproductivos en la adolescencia.</em>Buenos Aires: Paidós.</p>
                        <p><strong>Geldstein, R. N. y M. L. Schufer (2003) </strong>Ideología de género y comportamientos sexuales de los varones jóvenes de Buenos Aires. En: A. Mendes Diz, A. Federico, L. Findling y M. Abramzón (eds.), <em>IV Jornadas Nacionales de Debate Interdisciplinario en Salud y Población,</em>Instituto de Investigaciones Gino Germani, Facultad de Ciencias Sociales, Universidad de Buenos Aires, Buenos Aires (formato electrónico en CD).</p>
                        <p><strong>Pantelides, E. A. y H. Manzelli (2003) </strong>Investigación reciente sobre sexualidad y salud reproductiva de las/los adolescentes en América Latina: qué hemos alcanzado, qué falta hacer, cuáles son nuestras falencias. En: Cáceres, Cueto, Ramos y Vallenas (coords.) <em>La salud como derecho ciudadano. Perspectivas y propuestas desde América Latina.</em> Lima, Perú: International Forum for Social Sciences in Health, Universidad Peruana Cayetano Heredia- Fondo Editorial, Redess Jóvenes, pp.73-87.</p>
                        <p><strong>Pantelides, E. A. (2003) </strong><em>Aspectos sociales del embarazo y la fecundidad adolescente en América latina.</em> Trabajo presentado en el Seminario La fecundidad en América Latina: ¿transición o revolución?, organizado por el CELADE y el Centre de Recherche Populations et Sociétes, Université de Paris X-Nanterre, Santiago de Chile (Chile), 9-11 de junio.</p>
                        <p><strong>Pantelides, E. A. (2003) </strong><em>Vulnerabilidad y percepción de riesgo en jóvenes varones de 4 ciudades latinoamericanas.</em> Trabajo presentado en la XVII Reunión Bienal de la Asociación Latinoamericana de Investigadores en reproducción Humana (ALIRH), Varadero (Cuba), 28-31 de mayo.</p>
                        <p><strong>Geldstein, R. N. y M. L. Schufer (2002) </strong><em>Iniciación sexual y después. Prácticas e ideas de los varones jóvenes de Buenos Aires.</em> Buenos Aires: CENEP. <a href="http://www.cenep.org.ar/Iniciaci%C3%B3n%20sexual%20y%20despu%C3%A9s.pdf" target="_blank"><span style="color: #000000;">(link a pdf)</a></p>
                        <p><strong>Pantelides, E. A. (2002) </strong>Completing the Fertility Transition: the Case of Argentina. En:<em>United Nations, Population Division, Completing the Fertility Transition.</em> Nueva York: Naciones Unidas, pp. 333-342.</p>
                        <p><strong>Pantelides, E. A. (2002) </strong>Male Involvement in Prevention of Pregnancy and HIV Infection. En: <em>WHO, Programming for Male Involvement in Reproductive Health.</em> Ginebra: WHO, pp. 15-28.</p>
                        <p><strong>Pantelides, E. A. (2002) </strong>Conocimiento de métodos anticonceptivos y su uso en dos momentos de la vida sexual de varones jóvenes en Buenos Aires, La Habana, La Paz y Lima. Semejanzas y diferencias. En: Brache y Larrea (edits.), <em>Nuevas oportunidades de colaboración en investigación y desarrollo en salud reproductiva entre investigadores latinoamericanos y la industria</em> (Libro de resúmenes). S/l: Programa Latinoamericano de Capacitación e Investigación en Reproducción Humana (PLACIRH), 49-50.</p>
                        <p><strong>Geldstein, R. N. y E. A. Pantelides (2001) </strong><em>Riesgo reproductivo en la adolescencia. Desigualdad social y asimetría de género.</em> Buenos Aires: UNICEF Argentina, Cuadernos del UNICEF N° 8.</p>
                        <p><strong>Geldstein, R. N. y E. A. Pantelides (2001)</strong> <em>I didn’t want to but... Sexual initiation under coercion in the Buenos Aires Metropolitan Area.</em> En: International Union for the Scientific Study of Population (IUSSP) XXIV General Population Conference. Book of Abstracts. (Trabajo editado en CD ROM y en la página web: www.iussp.org).</p>
                        <p><strong>Geldstein, R. N. y E. A. Pantelides (2001) </strong><em>La iniciación sexual bajo coerción en el Área Metropolitana de Buenos Aires.</em> Buenos Aires: CENEP, Documento de trabajo N° 2.</p>
                        <p><strong>Geldstein, R. N. y M. L. Schufer (2001) </strong>Ideología de género y comportamientos sexuales de los varones jóvenes de Buenos Aires. En: <em>IV Jornadas Nacionales de Debate Interdisciplinario en Salud y Población.</em> Libro de Abstracts, Área Salud y Población, Instituto de Investigaciones Gino Germani, Facultad de Ciencias Sociales, Universidad de Buenos Aires (formato electrónico en CD).</p>
                        <p><strong>Geldstein, R. N., G. Infesta Domínguez y N. Delpino (2000) </strong>“La salud reproductiva de las adolescentes frente al espejo: discursos y comportamientos de madres e hijas”. En: Pantelides, E. A. y S. Bott (eds.) <em>Reproducción, salud y sexualidad en América Latina.</em> Buenos Aires: Biblos y Organización Mundial de la Salud - OMS.</p>
                        <p><strong>Pantelides, E. A. y S. Bott, eds. (2000) </strong><em>Reproducción, salud y sexualidad en América Latina.</em> Buenos Aires: Biblos-OMS.</p>
                        <p><strong>Pantelides, E. A. (2000) </strong>Introducción. En: E. A. Pantelides y S. Bott, (eds.) Reproducción, salud y sexualidad en América Latina. Buenos Aires: Biblos-OMS, pp.11-16.</p>
                        <p><strong>Pantelides, E. A., M. Gogna y S. Ramos (2000) </strong>Concepciones legas de salud y enfermedad: el SIDA según pobladores de un barrio pobre del Gran Buenos Aires. En: E. A. Pantelides y S. Bott (eds.) <em>Reproducción, salud y sexualidad en América Latina.</em> Buenos Aires: Biblos-OMS, pp.117-135.</p>
                        <p><strong>Pantelides, E. A., G. Infesta Domínguez y R. N. Geldstein (2000) </strong><em>Adolescent Women in Buenos Aires: the Influence of Social Class and Gender Images on Reproductive Behaviour.</em>En: B. García (ed.) Women, Poverty and Demographic Change. Oxford: Oxford University Press, pp.95-112.</p>
                        <p><strong>Geldstein, R. N. y G. Infesta Domínguez (1999) </strong>Las dos caras de la moneda: la salud reproductiva de las adolescentes en las miradas de las madres y las hijas. En: <em>AEPA, IV Jornadas Argentinas de Estudios de Población</em> (Resistencia, Chaco, 17-19 de octubre, 1995). Buenos aires: Dirección de Publicaciones del H. Senado de la Nación.</p>
                        <p><strong>Pantelides, E. A., R. N. Geldstein, N. Calandra y S. Vázquez (1999) </strong>“Iniciación sexual bajo coerción”. <em>Revista de la Sociedad Argentina de Ginecología Infanto-Juvenil,</em> 6 (3): 109-116.Pantelides, E. A., R. N. Geldstein, N. Calandra y S. Vázquez (1999) Ejercicio de la coerción en la iniciación sexual: la percepción desde las mujeres adolescentes. En: <em>Asociación Latinoamericana de Investigadores en Reproducción Humana (ALIRH),</em> XVI Reunión de la Asociación Latinoamericana de Investigaciones en Reproducción Humana. Libro de Resúmenes. Viña del Mar, Chile: ALIRH, pp. 86.AEPA, CEDES y CENEP (1998) Avances en la investigación social en salud reproductiva y sexualidad. Buenos Aires: AEPA – CEDES - CENEP.</p>
                        <p><strong>Infesta Domínguez, G. (1998)</strong> The implications of the researcher´s gender in the construction of data for studies on sexuality and masculine reproductive health. En: <em>Seminar on men, Family Formation and Reproduction.</em> Buenos Aires, Argentina, 13-14 May 1998. Paper. Lieja: IUSSP.</p>
                        <p><strong>Infesta Domínguez, G. (1998) </strong>La relación entre los estudios sobre reproducción y los estudios de género. En: S. Lerner, S. (ed.), <em>Varones, sexualidad y reproducción.</em> México: El Colegio de México, pp. 423-429.</p>
                        <p><strong>Infesta Domínguez, G. (1998) </strong>Varones adolescentes: los significados de la paternidad en la transición hacia los roles adultos. En: E. Bilac y M. I. Baltar de Rocha (orgs.) <em>Saúde Reprodutiva na América Latina e no Caribe: Temas e Problemas</em> (Programa Latinoamericano de Actividades de Población - PROLAP, Associaçao Brasileira de Estudos Populacionais - ABEP - NEPO/UNICAMP). Sao Pablo: Editora 34.</p>
                        <p><strong>Infesta Domínguez, G. y H. Manzelli (1998) </strong>El estudio de la participación del varón en la salud reproductiva: notas para la discusión. En: A. Méndes Diz, L. Findling, M. Petracci y A. Federico (comps.), <em>Salud y Población. Cuestiones Sociales Pendientes.</em> Buenos Aires: Espacio Editorial, pp. 69-86.</p>
                        <p><strong>Geldstein, R. N. y N. Delpino (1998) </strong>De madres a hijas. La transmisión de pautas de cuidado de la salud reproductiva. En: <em>AEPA, III Jornadas Argentinas de Estudios de Población</em>(Santa Rosa, La Pampa, 11-13 de octubre, 1995). Buenos Aires: Dirección de Publicaciones del H. Senado de la Nación.</p>
                        <p><strong>Mychaszula, S. M., J. L. Somoza y C. Donatti (1998) </strong>El método de la sobrevivencia de hermanas para estimar la mortalidad materna. Resultado de una aplicación y aportes metodológicos para mejorarlo. En: <em>III Jornadas argentinas de estudios de la población</em> (AEPA). Buenos Aires: H. Senado de la Nación, Secretaría Parlamentaria, Dirección Publicaciones.</p>
                        <p><strong>Pantelides, E. A. y R. N. Geldstein (1998) </strong>Encantadas, convencidas o forzadas: iniciación sexual en adolescentes de bajos recursos. En: <em>AEPA, CEDES, CENEP, Avances en la investigación en salud reproductiva y sexualidad.</em> Buenos Aires: AEPA, CEDES, CENEP, pp.45-53.</p>
                        <p><strong>Geldstein, R. N. y E. A. Pantelides (1997) </strong>"Double Subordination, Double Risk: Class, Gender and Sexuality in Adolescent Women in Argentina". <em>Reproductive Health Matters,</em> 9.58.</p>
                        <p><strong>Gogna, M., E. A. Pantelides, y S. Ramos (1997) </strong><em>Las enfermedades de transmisión sexual: género, salud y sexualidad.</em> Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 52.</p>
                        <p><strong>Pantelides, E. A. (1997) </strong>Diferenciales de fecundidad en la transición demográfica. En: H. G. Otero y G. A. Velázquez (comps.) <em>Poblaciones argentinas. Estudios de demografía diferencial.</em>Tandil, Argentina: Programa de Procesamiento de Información y Estudios de Población (PROPIEP), Instituto de Estudios Histórico Sociales (IEHS)-Centro de Investigaciones Geográficas (CIG), Facultad de Ciencias Humanas, Universidad Nacional del Centro de la Provincia de Buenos Aires, pp.29-39.</p>
                        <p><strong>Infesta Domínguez, G. (1996) </strong>Salud reproductiva y sexualidad: una visión desde la perspectiva del varón adolescente. En: <em>Segundo Taller de Investigaciones Sociales en Salud Reproductiva y Sexualidad.</em> Buenos Aires: Programa Regional sobre los Aspectos Sociales de la Reproducción Humana (PRASSAR) - CENEP/OMS; Programa Regional de Investigación Social, Entrenamiento y Asistencia Técnica en Salud Reproductiva y Sexualidad - CEDES y Comité Científico sobre Salud Reproductiva de la Asociación de Estudios de Población de la Argentina - AEPA.</p>
                        <p><strong>Geldstein. R. N. y E. A. Pantelides (1996)</strong> “Should we drain the Sea to Catch the Fish? Roundtable: Adolescent Pregnancy: when it is a Problem, what is the Solution?”.<em>Reproductive Health Matters,</em> 8: 112-113.</p>
                        <p><strong>Gogna, M., E. A. Pantelides y S. Ramos (1996) </strong>Sexualidad, género y prevención de las enfermedades de transmisión sexual. En: <em>Segundo Taller de Investigaciones Sociales en Salud Reproductiva y Sexualidad.</em> Buenos Aires: PRASSAR - CENEP/OMS, CEDES y AEPA, pp.79-84.</p>
                        <p><strong>Guzmán, J. M., S. Singh, G. Rodríguez y E. A. Pantelides, eds. (1996) </strong>The Fertility Transition in Latin America. Oxford: Clarendon Press.</p>
                        <p><strong>Pantelides, E. A., S. Ramos y M. Gogna (1996) </strong><em>Factores culturales y psicosociales en la prevención y el tratamiento de enfermedades de transmisión sexual.</em> En: I Seminario Taller Sudamericano. Investigación socio-cultural en sexualidad: prioridades y desafíos. Santiago de Chile: Equipo de Apoyo Técnico del FNUAP, Serie seminarios y talleres Nº 1, agosto, pp.82-84.</p>
                        <p><strong>Pantelides, E. A. (1996) </strong>A Century and a Quarter of Fertility Change in Argentina: 1869 to the Present. En: J. M. Guzmán, S. Singh, G. Rodríguez y E. A. Pantelides (eds.) <em>The Fertility Transition in Latin America.</em> Oxford: Clarendon Press, pp.345-358.</p>
                        <p><strong>Donatti, C., S. Mychaszula. y J. Somoza (1995) </strong>Avances en la aplicación del método del hijo previo. En: <em>1as. Jornadas argentinas de estudios de población.</em> Córdoba, Argentina: AEPA, Universidad Nacional de Córdoba.</p>
                        <p><strong>Mychaszula, S. M. (1995) </strong>Estimación de la mortalidad infantil de subpoblaciones de la ciudad de Zárate con técnicas que no utilizan estadísticas vitales. En: <em>II Jornadas argentinas de estudios de la población (AEPA).</em> Buenos Aires: H. Senado de la Nación, Secretaría Parlamentaria, Dirección Publicaciones.</p>
                        <p><strong>Pantelides, E. A. (1995) </strong><em>La maternidad precoz. La fecundidad adolescente en la Argentina.</em>Buenos Aires: UNICEF.</p>
                        <p><strong>Pantelides, E. A., R. N. Geldstein y G. Infesta Domínguez (1995) </strong><em>Imágenes de género y conducta reproductiva en la adolescencia.</em> Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 51.</p>
                        <p><strong>Pantelides, E. A. (1994) </strong>Adolescencia, fecundidad y conducta reproductiva. En: D. Celton (comp.) <em>Problemas de población en América Latina.</em> Córdoba, Argentina: Colección Debates, Centro de Estudios Avanzados, UNC, pp.65-71.</p>
                        <p><strong>Pantelides, E. A.., S. Ramos, J. O. Mormandi y O. Osores (1993) </strong>La deserción de pacientes con Papanicolaou positivo en hospitales públicos del Gran Buenos Aires. En: <em>Taller de Investigaciones Sociales en Salud Reproductiva y Sexualidad.</em> Buenos Aires: CENEP y CEDES. Sin paginación.</p>
                        <p><strong>Pantelides, E. A. (1993) </strong>Overview. Fertility Transitions in a Comparative Perspective. Documento de la organizadora de sesión. En: <em>IUSSP, International Population Conference.</em>Montreal (1), pp.3-10.</p>
                        <p><strong>Pantelides, E. A. y G. Binstock (1993) </strong>“Factores de riesgo de embarazo adolescente en el Paraguay”. <em>Revista Paraguaya de Sociología,</em> 30 (87): 171-186.</p>
                        <p><strong>Fogel, R. y E. A. Pantelides (1992) </strong><em>Determinantes principales del la fecundidad en áreas rurales de Paraguay: el caso de Itapúa.</em> Asunción: Centro de Estudios Rurales Interdisciplinarios.</p>
                        <p><strong>Mychaszula, S. M. y E. Kloster (1992) </strong>Crecimiento migratorio de la ciudad de Neuquén, cambio de la participación económica y del tamaño medio de la familia. En: <em>El poblamiento de las Américas.</em> Actas Vol 3. Veracruz, México: IUSPP et al.</p>
                        <p><strong>Pantelides, E. A. (1992) </strong>“Más de un siglo de fecundidad en la Argentina: su evolución desde 1869”. <em>Notas de Población,</em> 20 (56): 87-106.</p>
                        <p><strong>Pantelides, E. A. y M. S. Cerrutti (1992) </strong><em>Conducta reproductiva y embarazo en la adolescencia.</em> Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 47.</p>
                        <p><strong>Giusti, A. y E. A. Pantelides (1991) </strong><em>Fecundidad en la adolescencia. República Argentina 1980-1985.</em> Buenos Aires: Ministerio de Salud y Acción Social.</p>
                        <p><strong>Pantelides, E. A. (1990) </strong>Fecundidade e desenvolvimento. En: <em>República de Moçambique, Comissao Nacional do Plano, Direcçao Nacional de Estatística, Dinâmica demográfica e processos económicos, sociais e culturais.</em> Série Populaçao e Desenvolvimento, Documento Nº 2. Maputo, Mozambique: Comissao Nacional do Plano, Direcçao Nacional de Estatística, pp.9-17.</p>
                        <p><strong>Ramos, S. y E. A. Pantelides (1990)</strong> <em>Dificultades en la prevención secundaria del cáncer de cuello de útero: las mujeres y los médicos frente a una citología cervical de resultado positivo.</em> Buenos Aires: CEDES, Documento CEDES No 43.</p>
                        <p><strong>Ramos, S. y E. A. Pantelides (1990) </strong>“Prevención secundaria del cáncer de cuello de útero: determinantes de la deserción de pacientes”. <em>Cuadernos Médico Sociales,</em> 53: 37-50.</p>
                        <p><strong>Pantelides, E. A. (1989) </strong><em>La fecundidad argentina desde mediados del siglo XX (1989).</em>Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 41.</p>
                        <p><strong>Pantelides, E. A. (1989) </strong>“Fecundidad adolescente”. <em>Ciencia Hoy,</em> 1 (3): 71-72.</p>
                        <p><strong>Pantelides, E. A. (1986) </strong>“Notas respecto de la posible influencia de la inmigración europea sobre la fecundidad de la Argentina”. <em>Estudios Migratorios Latinoamericanos,</em> 1 (3): 351-356</p>
                        <p><strong>Pantelides, E. A. (1983) </strong>“La transición demográfica argentina: un modelo no ortodoxo”.<em>Desarrollo Económico,</em> 22 (88): 511-534. (También: Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 29.)</p>
                        <p><strong>Pantelides, E. A. (1982) </strong><em>Las mujeres de alta fecundidad en la Argentina: pasado y futuro.</em>Buenos Aires: CENEP, Serie Cuadernos del CENEP Nº 22.</p>
                        <p><strong>Wainerman, C. H. (1981) </strong>Female Work and Fertility in Argentina: Ideational Orientations and Actual Behaviour. En: <em>International Population Conference</em> (Manila, 1981). Lieja: IUSSP, pp. 557-570.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include("../inc/footer.php"); ?>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

</html>