<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CENEP</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="shortcut icon" type="image/png" href="/img/favicon.ico">
</head>

<body>
    <?php include("../../inc/header.php"); ?>

    <section class="body mx-auto">
        <div class="contenedor-body row">
            <?php include("../../inc/menues/areas-tematicas.php"); ?>

            <div class="body-texto col-md-9 p-5">
                <div class="contenedor-contenido">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a class="no-activo" href="/areas-tematicas/fecundidad.php">Fecundidad, salud reproductiva</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Comenzando a descifrar el misterio</li>
                        </ol>
                    </nav>
                    <div class="encabezado-separador">
                        <h1>Comenzando a descifrar el misterio: el compromiso del var&oacute;n en la salud reproductiva</h1>
                    </div>
                    <div class="texto">
                        <p><span class="subtitulo">reproductiva</a></li>Investigadora responsable:</span> Graciela Infesta Dom&iacute;nguez</p>
                        <p class="subtitulo">Resumen:</p>
                        <p>El estudio se propuso abordar los factores sociales, culturales y psicosociales que inciden en el comportamiento sexual y reproductivo de varones adultos. Es decir que el objetivo general de la investigaci&oacute;n tiene dos dimensiones, ya que intenta explorar y analizar: 1) las representaciones de los hombres respecto de su propia sexualidad y su funci&oacute;n reproductiva; 2) sus motivaciones para usar m&eacute;todos anticonceptivos como forma de prevenci&oacute;n de las enfermedades de transmisi&oacute;n sexual o de evitar un embarazo no planeado. El inter&eacute;s se centra especialmente en aquellas representaciones y motivaciones de los hombres vinculados con las relaciones asim&eacute;tricas de parejas y la doble moral sexual. Se ha optado por una aproximaci&oacute;n metodol&oacute;gica cualitativa. En una primera etapa se realizaron grupos de discusi&oacute;n y, luego, entrevistas en profundidad a varones de dos grupos de edad (entre los 25 y 35 a&ntilde;os, por un lado, y entre los 45 y 55 a&ntilde;os, por otro) pertenecientes a estratos socioecon&oacute;micos bajo y medio/alto. Este estudio representa la continuaci&oacute;n de otro en el que la investigadora abord&oacute; la forma en que esta problem&aacute;tica se manifiesta en varones adolescentes.</p>
                        <p>Durante la ejecuci&oacute;n del proyecto, el estudio incorpor&oacute; un nuevo objetivo de tipo metodol&oacute;gico, ya que se propuso analizar c&oacute;mo incide la mirada de g&eacute;nero del investigador/a en la construcci&oacute;n del dato obtenido a trav&eacute;s de grupos focales con varones. A tal fin, se dise&ntilde;&oacute; un cuasi-experimento que permiti&oacute; comparar la informaci&oacute;n obtenida en dos grupos focales de varones de 25 a 35 a&ntilde;os de estrato socioecon&oacute;mico medio/alto, los que fueron coordinados, en un caso, por la investigadora principal de la investigaci&oacute;n y, en el otro, por el asesor de la misma.</p>
                        <p>Los comportamientos y motivaciones de los hombres entrevistados en la investigaci&oacute;n cuyos resultados se presentan aqu&iacute;, no hicieron posible identificar un &uacute;nico tipo de carrera sexual y reproductiva (con especial referencia a las conductas preventivas y uso de m&eacute;todos anticonceptivos). Se estableci&oacute; que las diferencias observadas en los comportamientos y motivaciones de los hombres en la mencionada &aacute;rea no podr&iacute;an encuadrarse dentro del rango de &quot;variaciones&quot; esperables en cada fase de una carrera. Por el contrario, el material analizado revel&oacute; la existencia de distintos &quot;tipos&quot; de carreras, a saber: a) Tipo 1: El descuidado impulsivo, b) Tipo 2: El moralista sexual; c) Tipo 3: El usuario social y reparador; d) Tipo 4: El concientizado flexible; e) Tipo 5: El usuario pragm&aacute;tico; y f) Tipo 6: El cuidadoso cerebral. En cada uno de dichos &quot;tipos&quot; se subrayaron los aspectos comunes encontrados entre los entrevistados que permitieron construir el tipo puro, pero tambi&eacute;n se se&ntilde;alaron las variaciones que es posible encontrar al interior del mismo, las cuales no alteran lo esencial del tipo de carrera descripto.</p>
                        <p>El factor al que se atribuyen las principales diferencias encontradas entre los hombres entrevistados es la edad de los mismos: en tanto los varones del grupo de 25 a 35 a&ntilde;os se hab&iacute;an iniciado luego de la aparici&oacute;n del SIDA o, en el peor de los casos, apenas un poco antes de conocerse la existencia de dicha enfermedad, el grupo de los hombres de 45 a 55 a&ntilde;os vivieron su adolescencia y parte de su juventud sin el condicionante que la existencia del SIDA gener&oacute; en la vida sexual de las personas. Como consecuencia de esto, entre los hombres que utilizan preservativo, la formaci&oacute;n de conductas preventivas surgi&oacute; m&aacute;s tempranamente en el grupo de hombres m&aacute;s j&oacute;venes que en los varones del grupo de mayor edad. Se observa que entre los varones pertenecientes a diferentes grupos etarios existen diferencias marcadas a&uacute;n entre los pertenecientes al mismo estrato socioecon&oacute;mico, las cuales quedan especialmente reflejadas en el hecho de que los tipos de carrera que predominan en un grupo etario no son los mismos que predominan en el otro. M&aacute;s all&aacute; de esto, el estrato socioecon&oacute;mico al que pertenecen los hombres tambi&eacute;n permite explicar algunas diferencias importantes observadas en los comportamientos y motivaciones de los entrevistados. Cuando se comparan los varones de distinto estrato socioecon&oacute;mico pero igual grupo etario se observan algunas coincidencias: tanto entre los varones de estrato bajo como los del medio-alto que tienen entre 25 a 35 a&ntilde;os se encontraron casos en los que el uso de m&eacute;todos anticonceptivos responde al Tipo 2 de carrera; en forma similar, entre los hombres de estrato bajo y medio-alto de 45 a 55 a&ntilde;os es posible detectar el Tipo 4. Sin embargo, es importante se&ntilde;alar que a&uacute;n entre los hombres de la misma edad y del mismo nivel socioecon&oacute;mico se encontraron diferencias que, en algunos casos, son m&aacute;s importantes que las que determinan los dos factores mencionados en primer t&eacute;rmino.</p>
                        <p>En lo que respecta al objetivo metodol&oacute;gico que persigui&oacute; el estudio, los resultados indican que los grupos moderados por un var&oacute;n y los grupos moderados por una mujer producen insights complementarios. As&iacute;, por ejemplo, en el grupo moderado por un var&oacute;n, los participantes &quot;mostraron&quot; claramente su faceta de &quot;estrategas exitosos&quot; con las mujeres en tanto que en el grupo coordinado por una mujer pudieron hablar m&aacute;s sobres sus inseguridades, conflictos y &quot;p&eacute;rdidas&uml; frente a las mujeres. En tanto en el primer grupo los participantes resaltaron sus derechos en relaci&oacute;n con la reproducci&oacute;n, en el segundo enfatizaron sus responsabilidades con relaci&oacute;n a la misma. Comparativamente, los participantes del grupo coordinado por un var&oacute;n participaron m&aacute;s activamente en la dramatizaci&oacute;n de situaciones cotidianas en las que se planteaban conflictos en las relaciones de g&eacute;nero. A su vez, en el grupo coordinado por la investigadora los varones discutieron m&aacute;s profundamente cuestiones vinculadas a la sexualidad as&iacute; como las caracter&iacute;sticas de los procesos de toma de decisiones en relaci&oacute;n con diferentes &aacute;mbitos. Los resultados de este estudio indican que, al analizar las implicancias del g&eacute;nero del moderador en la producci&oacute;n de informaci&oacute;n, se debe tener en cuenta no s&oacute;lo el efecto que su sola presencia puede generar entre los participantes sino tambi&eacute;n la diferente capacidad de escucha que ambos pueden tener y que, indudablemente, va a incidir en la forma en que &eacute;l y ella van a conducir la discusi&oacute;n, los caminos por los cuales decidir&aacute;n avanzar en la indagaci&oacute;n y aquellos que descartar&aacute;n por considerar &quot;menos relevantes&quot;.</p>
                        <p>Esta investigaci&oacute;n constituy&oacute; uno de los primeros estudios realizados en el pa&iacute;s en el &aacute;rea de la salud sexual y reproductiva de los varones y se realiz&oacute; una importante difusi&oacute;n de sus resultados. Al incluir un objetivo de tipo metodol&oacute;gico, el estudio tambi&eacute;n contribuy&oacute; a reflexionar y llamar la atenci&oacute;n sobre aspectos vinculados a los m&eacute;todos que utilizamos los cient&iacute;ficos para producir conocimiento, as&iacute; como las condiciones en que este &uacute;ltimo se produce.</p>
                        <p>La investigaci&oacute;n cont&oacute; con un subsidio del Health Reproductive Program de la Organizaci&oacute;n Mundial de la Salud, al que se accedi&oacute; por concurso.</p>
                        <p class="subtitulo">Difusi&oacute;n de resultados:</p>
                        <p><strong>Infesta Dom&iacute;nguez, G. (2005)</strong> Decisiones anticonceptivas en la pareja desde la perspectiva de varones adultos. En: Pantelides, E. A. y E. L&oacute;pez (comps.), Varones latinoamericanos. Estudios sobre sexualidad y reproducci&oacute;n. Buenos Aires: Paid&oacute;s, pp. 145-173.<br>
                            <strong>Alvarez, L., A. Rodr&iacute;guez, G. Infesta Dom&iacute;nguez y J. L. Calero (2004)</strong> Enfoque metodol&oacute;gico cualitativo en las Investigaciones en Salud Sexual y Reproductiva. En: L. Alvarez, y A. Rodr&iacute;guez (coords.), La Investigaci&oacute;n en Salud Sexual y Reproductiva: propuestas metodol&oacute;gicas y experiencias. La Habana: UNFPAP/OMS, pp. 50-71.<br>
                            <strong>Alvarez, L., A. Rodr&iacute;guez y G. Infesta Dom&iacute;nguez (2004)</strong> Enfoque metodol&oacute;gico combinado en las investigaciones en Salud Sexual y Reproductiva. En: L. Alvarez y A. Rodr&iacute;guez (coords.), La investigaci&oacute;n en Salud Sexual y Reproductiva: propuestas metodol&oacute;gicas y experiencias. La Habana: UNFPA/OMS, pp. 72-83.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (2003)</strong> Conductas de cuidado de la salud sexual y reproductiva en varones adultos: una cuesti&oacute;n de carreras. En: A. Mendes Diz, A. Federico, L. Findling y M. Abramz&oacute;n (eds.), IV Jornadas Nacionales de Debate Interdisciplinario en Salud y Poblaci&oacute;n, Instituto de Investigaciones Gino Germani, Facultad de Ciencias Sociales, Universidad de Buenos Aires, Buenos Aires (formato electr&oacute;nico en CD)<br>
                            <strong>Infesta Dom&iacute;nguez, G. (2003)</strong> Pr&aacute;cticas preventivas del embarazo no planeado y VIH/SIDA en varones adultos: conductas y actitudes relacionados con la utilizaci&oacute;n de m&eacute;todos anticonceptivos (con especial referencia al preservativo). Trabajo presentado a la XVIII Reuni&oacute;n Bienal de la Asociaci&oacute;n Latinoamericana de Investigadores en Reproducci&oacute;n Humana (ALIRH), Varadero, 28 al 31 de mayo.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (2003)</strong> La construcci&oacute;n de la masculinidad: la cuesti&oacute;n del padre. Trabajo presentado al Seminario Mujeres y Varones. Subjetividad y g&eacute;nero, Profs.: Sandra Borakievich y D&eacute;bora Tajer, Secretar&iacute;a de Posgrado, Facultad de Psicolog&iacute;a, Universidad de Buenos Aires, Buenos Aires.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (2001)</strong> Los varones y el sexo seguro: una cuesti&oacute;n de carreras sexuales y reproductivas. Trabajo presentado en las IV Jornadas Nacionales de Debate Interdisciplinario en Salud y Poblaci&oacute;n, organizadas por el Area de Salud y Poblaci&oacute;n del Instituto de Investigaciones Gino Germani de la Facultad de Ciencias Sociales de la Universidad de Buenos Aires, a realizarse entre el 8 y 10 de agosto.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (2001)</strong> La red invisible: masculinidad, sexualidad y salud reproductiva. Trabajo presentado en LASA 2001, XXIII International Congress of the Latin American Studies Association, 6-8 de septiembre, Washington, D.C.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (1998)</strong> The implications of the researcher&acute;s gender in the construction of data for studies on sexuality and masculine reproductive health. En: Seminar on men, Family Formation and Reproduction. Buenos Aires, Argentina, 13-14 May 1998. Paper. Lieja: IUSSP.<br>
                            Infesta Dom&iacute;nguez, G. y H. Manzelli (1998) El estudio de la participaci&oacute;n del var&oacute;n en la salud reproductiva: notas para la discusi&oacute;n. En: A. M&eacute;ndes Diz, L. Findling, M. Petracci y A. Federico (comps.), Salud y Poblaci&oacute;n. Cuestiones Sociales Pendientes. Buenos Aires: Espacio Editorial, pp. 69-86.<br>
                            <strong>Infesta Dom&iacute;nguez, G. (1998)</strong> La relaci&oacute;n entre los estudios sobre reproducci&oacute;n y los estudios de g&eacute;nero. En: S. Lerner, S. (ed.), Varones, sexualidad y reproducci&oacute;n. M&eacute;xico: El Colegio de M&eacute;xico, pp. 423-429.
                        </p>
                        </td>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include("../../inc/footer.php"); ?>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

</html>